import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import MainWrapper from "@/components/wrappers/main-wrapper";
import Navbar from "@/components/navigation/navbar";
import ThemeToggle from "@/components/theme/theme-toggle";
import Breadcrumb from "@/components/navigation/breadcrumb";

export const metadata = {
    title: "Portfolio | Valentin Arnould",
    description: "Generated by create next app",
};

export default function RootLayout({ children }){
    return (
        <html lang="fr">
            <body>
                <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                >
                    <MainWrapper>
                        <Navbar/>
                        <Breadcrumb/>
                        {children}
                        <ThemeToggle className={"absolute bottom-4 right-4"}/>
                    </MainWrapper>
                </ThemeProvider>
            </body>
        </html>
    );
}
